version: "3.9"

services:
  listener:
    dns:
      - "172.31.0.2"
      - "8.8.8.8"

  web_server:
    dns:
      - "172.31.0.2"
      - "8.8.8.8"

  web_server_2:
    dns:
      - "172.31.0.2"
      - "8.8.8.8"

  job_master:
    dns:
      - "172.31.0.2"
      - "8.8.8.8"

  rec-worker:
    dns:
      - "172.31.0.2"
      - "8.8.8.8"

  postgres:
    dns:
      - "172.31.0.2"
      - "8.8.8.8"

  redis:
    dns:
      - "172.31.0.2"
      - "8.8.8.8"
